% === PARAMETER 2: ELECTRICAL POWER SYSTEM (EPS) ===
function eps = EPS_sim(correction)

persistent sim_time current_charge_wh

if nargin < 1
    correction = [];
end

if isempty(current_charge_wh)
    current_charge_wh = 0.06;    % Changed this to 0.6
    sim_time = 0;
end

% Simulation Controls
dt = 5;             % Time step size (seconds)
sim_time = sim_time + dt;


% Base Systems (always on)
power_base_draw = 1.5;          % Constant draw from flight computer

% Optional systesm
power_thermal = 0.5;            % Thermal regulation ADDED THIS
power_payload = 0.8;            % Payload instrument ADDED THIS
power_attitude = 0.6;           % Reaction wheels / ADCS ADDED THIS
power_comms_draw = 3.0;         % Extra spike when sending MQTT packets

solar_generation = 7;           % Power generated by panels in the sun 
% ^^^^Edited this from 4.0      % For a perfect cycle from 30-100; changed to 7  

% Battery Specifications (Standard 1U)
battery_capacity_wh = 0.06;     % Total capacity in Watt-hours; Changed this to 0.6 

% --- SIMULATE ORBITAL ENVIRONMENT ---
% Fast-forward orbit cycle for testing: 60s in Sun, 30s in Eclipse

if mod(sim_time, 90) < 60
    in_sunlight = true;
    
else
    in_sunlight = false;
    
end

% **************** Added this section for corrections **************************

if ~isempty(correction)

    if correction.disable_payload
        power_payload = 0;
    end

    if correction.disable_attitude_control
        power_attitude = 0;
    end

    if correction.safe_mode
        %reduce computer power usage
        power_base_draw = 0.2;
        power_payload =0;
        power_thermal = 0.2;
        power_attitude = 0;
    end

    if correction.emergency_power
        % emergency mode shuts down almost everything non essential
        power_payload = 0;
        power_attitude = 0;
        power_base_draw = power_base_draw * 0.3;
    end
end

%*****************************************************************

% --- CALCULATE NET POWER ---
total_draw = power_base_draw + power_payload + power_attitude + power_thermal;

if in_sunlight
    net_power = solar_generation - total_draw;
else
    net_power = -total_draw; % No solar power, only drawing
end

% Simulate a data transmission spike every 10 seconds
if mod(sim_time, 10) == 0
    net_power = net_power - power_comms_draw;
    
end

% --- UPDATE BATTERY CHARGE ---
% Convert Watts (Joules/sec) to Watt-hours for the time step

charge_change = net_power * (dt / 3600); 

current_charge_wh = current_charge_wh + charge_change;

% Limits: Battery cannot exceed 100% or drop below 0%

if current_charge_wh > battery_capacity_wh

    current_charge_wh = battery_capacity_wh;

elseif current_charge_wh < 0

    current_charge_wh = 0;
    
end

% Convert to Percentage for the telemetry JSON dictionary
battery_pct = (current_charge_wh / battery_capacity_wh) * 100;

eps.time = sim_time;

eps.battery_percent = battery_pct;

eps.power_consumption_w = net_power;

eps.in_sunlight = in_sunlight;

end