% === PARAMETER 3: THERMAL CONTROL SYSTEM (TCS) ===
function thermal = thermal_sim(correction)

persistent T_kelvin sim_time

if nargin < 1
    correction = [];
end

if isempty(T_kelvin)

    T_kelvin = 293.15;
    sim_time = 0;

end

dt = 5;               % Time step (seconds)
sim_time = sim_time + dt;

% CubeSat Thermal Properties (1U Aluminum Frame)
mass = 1.33;            % kg (Standard 1U mass)
Cp = 900;               % Specific heat capacity of Aluminum (J/kg*K)
thermal_mass = mass * Cp; 
A_sun = 0.01;           % Cross-sectional area facing the sun (m^2)
A_total = 0.06;         % Total surface area radiating heat out (m^2)
alpha = 0.8;            % Solar absorptivity (How much sun it absorbs)
epsilon = 0.8;          % IR emissivity (How much heat it radiates); increased it a bit 
sigma = 5.67e-8;        % Stefan-Boltzmann constant

% Space Environment Constants
solar_flux = 1361;      % Sun's energy at Earth's orbit (W/m^2)
T_space = 3;            % Deep space background temperature (Kelvin)

% --- SIMULATE ORBITAL ENVIRONMENT ---
% Fast-forward orbit cycle: 60s in Sun, 30s in Eclipse
if mod(sim_time, 90) < 60
    % Heat coming in from the Sun
    Q_sun = solar_flux * A_sun * alpha;

else
    % Blocked by Earth, no sun
    Q_sun = 0;

end

% Heat generated by your own internal electronics (approx 1.5 Watts)
Q_internal = 1.5; %simulating heater/cooler adjustements (assuming cubesat has
%component that regulates the temp)

% **************** Added this section for corrections **************************
Q_control = 0;

if ~isempty(correction)
    %it IS making it to this part of the code, difference of 1.0 is not
    %enough
    disp(correction.heater)
    disp(correction.cooler)

    if correction.heater
        Q_control = Q_control + 20.0; %Watts
    end

    if correction.cooler 
        Q_control = Q_control - 20.0; %Watts
    end
end    
% ****************************************************************


% Heat radiating out into the freezing vacuum of space
Q_out = epsilon * sigma * A_total * (T_kelvin^4 - T_space^4);

% --- CALCULATE TEMPERATURE CHANGE ---
% Heat In = Sun + Electronics + Heater
% Heat In = Sun + Electronics - Cooler 

Q_net = Q_sun + Q_internal + Q_control - Q_out; 	%Q_control added here for corrections
delta_T = (Q_net / thermal_mass) * dt; 

% Update Temperature
T_kelvin = T_kelvin + delta_T;

thermal.temperature_c = T_kelvin-273.15;

end